version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4

    branches:
      only:
        - master
    
    working_directory: ~/repo
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            coverage run --source=templot --omit=tests/test_*.py -m unittest discover tests

      - run:
          name: flake8
          command: |
            . venv/bin/activate
            python -m flake8 tests --ignore=E501,W503
            python -m flake8 templot --ignore=E501,W503
            python -m flake8 examples --ignore=E501,W503

      - run:
          name: coverage
          command: |
            . venv/bin/activate
            coverage html -d dist/html/coverage.html

      - run:
          name: wheel
          command: |
            . venv/bin/activate
            python setup.py bdist_wheel
            cp dist/*.whl dist/html

      - run:
          name: documentation
          command: |
            . venv/bin/activate
            sphinx-build -M html doc dist/html

      - store_artifacts:
          path: dist/html
          destination: dist